name: download-release-asset
description: Download an asset from a GitHub Release

inputs:
  github-token:
    description: 'A token with permission to download assets from repository releases'
    required: true
  asset-name:
    description: 'The name of the release asset'
    required: true
  tag-name:
    description: 'The tag associated with the release that contains the asset to download. You may also use the tag name "latest".'
    required: true
  repository:
    description: 'The organization/repository to download the release asset from.  If not provided, defaults to github.repository'
    required: false

outputs:
  download-file-path:
    description: 'Full file path of download asset'
  error-condition:
    description:  'Describes the error condition if the action fails'

runs:
  using: 'node20'
  main: 'dist/index.js'
